# This is a generated file. Not intended for manual editing.
version: "3.8"
services:
  api:
    build:
      context: "/home/jpcalsavara/projetos/andamento/InterceptorSystem/src"
      dockerfile: "InterceptorSystem.Api/Dockerfile"
      target: "build"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/InterceptorSystem.Api.dll"
    environment: {}
    image: "interceptorsystem.api:dev"
    ports: []
    volumes:
    - "/home/jpcalsavara/projetos/andamento/InterceptorSystem/src/InterceptorSystem.Api:/app:rw"
    - "/home/jpcalsavara/projetos/andamento/InterceptorSystem/src:/src:rw"
    - "/home/jpcalsavara/.nuget/packages:/root/.nuget/packages"
    working_dir: "/app"
