services:
  # --- BANCO DE DADOS (Relacional/Core) ---
  db:
    image: postgres:15-alpine
    container_name: interceptor_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: interceptor_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - interceptor-network

  # --- API .NET (Backend) ---
  api:
    build:
      context: .
      dockerfile: InterceptorSystem.Api/Dockerfile
    container_name: interceptor_api
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=interceptor_db;Username=admin;Password=password123
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db
    networks:
      - interceptor-network
    # Não expomos a porta 8080 para o host. Só o Nginx fala com a API.
    expose:
      - "8080"

  # --- LOAD BALANCER / REVERSE PROXY ---
  nginx:
    image: nginx:alpine
    container_name: interceptor_nginx
    ports:
      - "80:80"  # O mundo acessa a porta 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    networks:
      - interceptor-network

volumes:
  postgres_data:

networks:
  interceptor-network:
    driver: bridge